config/routes.rb
Biblio::Application.routes.draw do
  devise_for :views

  resources :books

  devise_for :users

  resources :pages

  root to: "pages#index"

end

app/models/book.rb
class Book < ActiveRecord::Base

  mount_uploader :cover, PictureUploader
  
  attr_accessible :author, :catagory, :cover, :description, :isbn, :published, :rating, :title
  
  belongs_to :user

  if not :isbn.blank?
  	before_create do 
  		client = Goodreads::Client.new(:api_key => 'fJ9s57rL9axejFqpiW3g', :api_secret => 'evEy1rsq9nxBRlnpXUzkskEhqNx6RhB1Lrmcpj0fBJE')
  		book = client.book_by_isbn(self.ISBN)
  		self.title = book.title if self.title.blank?
      if self.author.blank?
        if book.authors.author.is_a?(Array)
          self.author = book.authors.author[0].name
        else 
          self.author = book.authors.author.name
        end
      end
      self.description = Sanitize.clean(book.description) if self.description.blank?
      self.goodreadscover = book.image_url
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :email, :username, :password
  has_many :books
end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # GET /books
  # GET /books.json
  def index
    @books = current_user.books

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = current_user.books.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/new
  # GET /books/new.json
  def new
    @book = Book.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @book }
    end
  end

  # GET /books/1/edit
  def edit
    @book = Book.find(params[:id])
  end

  # POST /books
  # POST /books.json
  def create
    @book = current_user.books.build(params[:book])

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render json: @book, status: :created, location: @book }
      else
        format.html { render action: "new" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /books/1
  # PUT /books/1.json
  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update_attributes(params[:book])
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book = Book.find(params[:id])
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	  @books = Book.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @books }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/books/_form.html.erb
<%= form_for(@book, :html => { :multipart => true }) do |f| %>

  <% if @book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :published %><br />
    <%= f.date_select :published %>
  </div>
  <div class="field">
    <%= f.label :catagory %><br />
    <%= f.text_field :catagory %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br />
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :cover %><br />
    <%= f.file_field :cover %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render 'form' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<div class="mylist">
  <h1>Your Books</h1>
</div>
<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Published</th>
    <th>Category</th>
    <th>Description</th>
    <th>Rating</th>
    <th>Isbn</th>
    <th>Cover</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.author %></td>
    <td><%= book.published %></td>
    <td><%= book.catagory %></td>
    <td><%= book.description %></td>
    <td><%= book.rating %></td>
    <td><%= book.isbn %></td>
    <td><%= image_tag(book.cover_url, width: 50) if book.cover.present? %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Book', new_book_path, class: "btn btn-primary" %>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render 'form' %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @book.title %>
</p>

<p>
  <b>Author:</b>
  <%= @book.author %>
</p>

<p>
  <b>Published:</b>
  <%= @book.published %>
</p>

<p>
  <b>Catagory:</b>
  <%= @book.catagory %>
</p>

<p>
  <b>Description:</b>
  <%= @book.description %>
</p>

<p>
  <b>Rating:</b>
  <%= @book.rating %>
</p>

<p>
  <b>Isbn:</b>
  <%= @book.isbn %>
</p>

<p>
  <b>Cover:</b>
  <%= image_tag(@book.cover_url) if @book.cover.present? %>
</p>


<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BiblioPhile</title>
  
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application", :media => "all" %>
</head>
<body>
	<% if flash[:notice] %>
		<div class="alert"><%= notice %></div>
	<% end%>
	<% if flash[:alert] %>
		<div class="alert alert-error"><%= alert %></div>
	<%end%>
	<div id="container">
		<nav class="navbar">
	    <div class="navbar-inner">
	      <a class="brand" href="/">BiblioPhile</a>
	      <ul class="nav pull-right">
	        <% if current_user.present? %>
	        <%# user is logged in, show log out link, user tasks, create new task %>
	          <li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
	          <li><%= link_to 'My Books', books_path %></li> 
	          <li><%= link_to 'Add Book', new_book_path %></li>
	        <%# user is not logged in, show signup and login links %>
	        <% else %>
	          <li><%= link_to 'Sign In', new_user_session_path %></li> 
	          <li><%= link_to 'Register Now!', new_user_registration_path %></li>
	        <% end %>
	      </ul>
	    </div>
	  </nav>
  </div>
<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/pages/index.html.erb
<div class="banner">
	<h3>Welcome to the BibloPhile App!</h3>
	<p>A great way to store and share your favorite reads. <br>
    1) Check out all the books that have been added by other users on the <b>Master List</b> <br>
    2) Register as a member to maintain your own personal list while adding to the collective <b>Master List!</b>

  </p>
	<a class="btn btn-primary register" href="/users/sign_up">Register</a>
</div>

</br >
<h3>Master List</h3>
<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th>Author</th>
    <th>Published</th>
    <th>Category</th>
    <th>Description</th>
    <th>Rating</th>
    <th>Isbn</th>
    <th>Cover</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @books.each do |book| %>
  <tr>
    <td><%= book.title %></td>
    <td><%= book.author %></td>
    <td><%= book.published %></td>
    <td><%= book.catagory %></td>
    <td><%= book.description %></td>
    <td><%= book.rating %></td>
    <td><%= book.isbn %></td>
    <td><%= image_tag(book.cover_url, width: 50) if book.cover.present? %></td>
    <td><%= link_to 'Show', book %></td>
    <td><%= link_to 'Edit', edit_book_path(book) %></td>
    <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>